//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DicEspNahuatl.Datos.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CamposConstantes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CamposConstantes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DicEspNahuatl.Datos.Recursos.CamposConstantes", typeof(CamposConstantes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaveEntidad.
        /// </summary>
        public static string C_ClaveEntidad {
            get {
                return ResourceManager.GetString("C_ClaveEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaveEstado.
        /// </summary>
        public static string C_ClaveEstado {
            get {
                return ResourceManager.GetString("C_ClaveEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        public static string C_Comentarios {
            get {
                return ResourceManager.GetString("C_Comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espaniol.
        /// </summary>
        public static string C_Espaniol {
            get {
                return ResourceManager.GetString("C_Espaniol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FechaCambio.
        /// </summary>
        public static string C_FechaCambio {
            get {
                return ResourceManager.GetString("C_FechaCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string C_Id {
            get {
                return ResourceManager.GetString("C_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen.
        /// </summary>
        public static string C_Imagen {
            get {
                return ResourceManager.GetString("C_Imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificaciones.
        /// </summary>
        public static string C_Modificaciones {
            get {
                return ResourceManager.GetString("C_Modificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahuatl.
        /// </summary>
        public static string C_Nahuatl {
            get {
                return ResourceManager.GetString("C_Nahuatl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjetoLectura.
        /// </summary>
        public static string C_ObjetoLectura {
            get {
                return ResourceManager.GetString("C_ObjetoLectura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string C_Tipo {
            get {
                return ResourceManager.GetString("C_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string C_Url {
            get {
                return ResourceManager.GetString("C_Url", resourceCulture);
            }
        }
    }
}
