//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DicEspNahuatl.Datos.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DicEspNahuatl.Datos.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string C_Activo {
            get {
                return ResourceManager.GetString("C_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha agregado una nueva categoria.
        /// </summary>
        public static string C_AgregarCategoria {
            get {
                return ResourceManager.GetString("C_AgregarCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha agregado un nuevo comercio.
        /// </summary>
        public static string C_AgregarComercio {
            get {
                return ResourceManager.GetString("C_AgregarComercio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgregarModificar.
        /// </summary>
        public static string C_AgregarModificar {
            get {
                return ResourceManager.GetString("C_AgregarModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaveEntidad.
        /// </summary>
        public static string C_ClaveEntidad {
            get {
                return ResourceManager.GetString("C_ClaveEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha editado la informacion de la categoria.
        /// </summary>
        public static string C_EdicionCategoria {
            get {
                return ResourceManager.GetString("C_EdicionCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha editado la informacion del comercio.
        /// </summary>
        public static string C_EdicionComercio {
            get {
                return ResourceManager.GetString("C_EdicionComercio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FechaCambio.
        /// </summary>
        public static string C_FechaCambio {
            get {
                return ResourceManager.GetString("C_FechaCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        public static string C_Inactivo {
            get {
                return ResourceManager.GetString("C_Inactivo", resourceCulture);
            }
        }
    }
}
