//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DicEspNahuatl.Datos.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParametrosConstantes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParametrosConstantes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DicEspNahuatl.Datos.Recursos.ParametrosConstantes", typeof(ParametrosConstantes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VClaveEntidad.
        /// </summary>
        public static string PC_ClaveEntidad {
            get {
                return ResourceManager.GetString("PC_ClaveEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VClaveEstado.
        /// </summary>
        public static string PC_ClaveEstado {
            get {
                return ResourceManager.GetString("PC_ClaveEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VComentarios.
        /// </summary>
        public static string PC_Comentarios {
            get {
                return ResourceManager.GetString("PC_Comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EsNahuatl.
        /// </summary>
        public static string PC_DataBase {
            get {
                return ResourceManager.GetString("PC_DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VEspaniol.
        /// </summary>
        public static string PC_Espaniol {
            get {
                return ResourceManager.GetString("PC_Espaniol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.
        /// </summary>
        public static string PC_EsquemaLS {
            get {
                return ResourceManager.GetString("PC_EsquemaLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VFechaCambio.
        /// </summary>
        public static string PC_FechaCambio {
            get {
                return ResourceManager.GetString("PC_FechaCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VId.
        /// </summary>
        public static string PC_Id {
            get {
                return ResourceManager.GetString("PC_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VImagen.
        /// </summary>
        public static string PC_Imagen {
            get {
                return ResourceManager.GetString("PC_Imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VNahuatl.
        /// </summary>
        public static string PC_Nahuatl {
            get {
                return ResourceManager.GetString("PC_Nahuatl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VNOPCION.
        /// </summary>
        public static string PC_NOPCION {
            get {
                return ResourceManager.GetString("PC_NOPCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VTipo.
        /// </summary>
        public static string PC_Tipo {
            get {
                return ResourceManager.GetString("PC_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VUrl.
        /// </summary>
        public static string PC_Url {
            get {
                return ResourceManager.GetString("PC_Url", resourceCulture);
            }
        }
    }
}
